#!/usr/bin/env bash
#Displays domain information
if [ "$#" -eq 1 ]
then
	d="www.$1 lb-01.$1 web-01.$1 web-02.$1"
else
	d="$2.$1"
fi

dig $d | awk '/ANSWER SECTION:/{getline; split($1,b,"."); print "The subdomain", b[1], "is a", $4, "record and points to", $5}'

