#!/usr/bin/env bash
# Installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo mkdir /var/www/page1
echo "Hello World!" > /var/www/page1/index.nginx-debian.html
sudo service nginx start
