#!/usr/bin/env bash
# Installs nginx
#apt-get -y update
#apt-get -y install nginx
sudo chown ubuntu /var/www/html/index.nginx-debian.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.holbertonschool.com permanent;" /etc/nginx/sites-available/default
sudo service nginx start
