#!/usr/bin/env bash
#Configures a new http header
sudo apt-get install nginx
sudo cp /etc/nginx/nginx.conf{,.original}
sudo cp /etc/nginx/sites-available/default{,.original}
sudo sed -I "20i\	add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
