#!/usr/bin/env bash
#Configures HAProxy
sudo ssh -i ~/.ssh/school ubuntu@100.26.171.143 sudo apt-get install haproxy
sudo ssh -i ~/.ssh/school ubuntu@100.26.171.143 sudo mv /etc/haproxy/haproxy.cfg{,.original}
#sudo ssh -i ~/.ssh/school ubuntu@100.26.171.143 sudo chown ubuntu /etc/haproxy/haproxy.cfg
sudo sed -i 's|ENABLED=0|ENABLED=1|' /etc/default/haproxy
#echo "ENABLED=1" >  /etc/default/haproxy
sudo ssh -i ~/.ssh/school ubuntu@100.26.171.143 sudo echo "\n\nfrontend myfrontend\n\tmode http\n\tbind 100.26.171.143:80\n\tdefault_backend web_servers\nbackend web_servers\n\tmode http\n\tbalance roundrobin\n\toption httpchk\n\tserver 7319-web-01 54.242.195.19[:80] check\n\tserver 7319-web-02 54.236.50.27[:80] check" >> /etc/haproxy/haproxy.cfg
