#!/usr/bin/env bash
file="/etc/passwd"
IFS=:
while read -r line;
do
	echo "The user $(cut -d -f1 <<< "$line") is part of the $(cut -f4 <<< "$line") gang, lives in $(cut -f6 <<< "$line") and rides COMMAND/SHELL. $(cut -f3 <<< "$line")'s place is protected by the passcode $(cut -f2 <<< "$line"), more info about the user here: $(cut -f5 <<< "$line")"
done <$file
