#!/usr/bin/env bash
#Prints "Best School" 10 times and "bad luck" on the 4 turn and "good luck" on the 8th turn.
i=1
while [ $i -le 10 ];
do
	if [ $i -ne 4 ] && [ $i -ne 8 ]
	then
		echo "Best School"
	elif [ $i == 4 ]
	then
		echo "bad luck"
	else
		echo "good luck"
	fi
	((i++))
done
