#!/usr/bin/env bash
f="school"
if [ -e "$f" ]
then
	echo "school file exists"
	if [ ! -s "$f" ]
	then
		echo "school file is empty"
	fi
	if [ -s "$f" ]
	then
		echo "school file is not empty"
	fi
	if [ -f "$f" ]
	then
		echo "school is a regular file"
	fi
fi
if [ ! -e "$f" ]
then
	echo "school file does not exist"
fi

